### ISSUE TITLE
Add example output.

### ISSUE THREAD

**Issue by perrygoy** [ScreenPyHQ/screenpy_adapter_allure#2]
There's currently no example output to see what the Allure report will look like after attaching this Adapter.

Add some screenshots or something! Probably of the report generated by the [Guided Example](https://screenpy-docs.readthedocs.io/en/latest/example.html) in ScreenPy's documentation.

**Comment by Scot3004** [comment]
I'm working on it using the [github example](https://github.com/ScreenPyHQ/screenpy_examples/tree/trunk/screenpy_selenium/github) that uses this adapter, as well is useful to understand the example referenced in the issue https://github.com/ScreenPyHQ/screenpy_selenium/issues/23

**Comment by perrygoy** [comment]
Thanks @Scot3004!
