### ISSUE TITLE
module 'screenpy.narration.narrator' has no attribute 'AIRY'

### ISSUE THREAD

**Issue by bandophahita** [ScreenPyHQ/screenpy_adapter_allure#4]
The following exception occurs when trying to run the tests in [screenpy_examples.screenpy_selenium.github.features](https://github.com/ScreenPyHQ/screenpy_examples/tree/trunk/screenpy_selenium/github/features) using 4.0.2 of screenpy_adapter_allure.

```
ImportError while loading conftest '/projects/screenpy_examples/screenpy_selenium/github/features/conftest.py'.
conftest.py:2: in <module>
    from screenpy_adapter_allure import AllureAdapter
../../../../../.pyenv/versions/screenpy_examples/lib/python3.11/site-packages/screenpy_adapter_allure/__init__.py:16: in <module>
    from .adapters import AllureAdapter
../../../../../.pyenv/versions/screenpy_examples/lib/python3.11/site-packages/screenpy_adapter_allure/adapters.py:17: in <module>
    class AllureAdapter:
../../../../../.pyenv/versions/screenpy_examples/lib/python3.11/site-packages/screenpy_adapter_allure/adapters.py:23: in AllureAdapter
    narrator.AIRY: allure.severity_level.TRIVIAL,
E   AttributeError: module 'screenpy.narration.narrator' has no attribute 'AIRY'
```

**Comment by Scot3004** [comment]
When do you think we can have a new release with this change?

**Comment by perrygoy** [comment]
We're working on an update to ScreenPy that will make it easier to import things from the base level, and that should hopefully be ready to release later this week. I'll make sure releasing this happens right after that!

**Comment by perrygoy** [comment]
Fixed in #5! Thanks, @Scot3004!

**Comment by perrygoy** [comment]
Hey @Scot3004, we didn't get our new version of ScreenPy deployed this week. So you don't have to wait, i'll just release a minor version tonight when my kids get to sleep so you'll have it ready for Monday. We can release another minor version when we get the nifty ScreenPy stuff deployed as well!

**Comment by perrygoy** [comment]
@Scot3004 OK, 4.0.3 has just been published! Thanks again for your help, publishing with `poetry` worked perfectly!
